name: github-page-release-workflow
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  release:
    types: [created]
permissions:
    id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - uses: actions/deploy-pages@v1
        with:
          token: ${{ github.token }}
  
